#
# Table structure for table 'tt_content'
#
CREATE TABLE tt_content (
	singleimage_1 int(11) unsigned DEFAULT '0' NOT NULL,
	singleimage_2 int(11) unsigned DEFAULT '0' NOT NULL,
	singleimage_3 int(11) unsigned DEFAULT '0' NOT NULL,
	singleimage_4 int(11) unsigned DEFAULT '0' NOT NULL,
	singleimage_5 int(11) unsigned DEFAULT '0' NOT NULL,
	singleimage_6 int(11) unsigned DEFAULT '0' NOT NULL,
	singlefile_1 int(11) unsigned DEFAULT '0' NOT NULL,
	singlefile_2 int(11) unsigned DEFAULT '0' NOT NULL,
	singlefile_3 int(11) unsigned DEFAULT '0' NOT NULL,
	singlefile_4 int(11) unsigned DEFAULT '0' NOT NULL,
	singlefile_5 int(11) unsigned DEFAULT '0' NOT NULL,
	singlefile_6 int(11) unsigned DEFAULT '0' NOT NULL,
	multiplefiles_1 int(11) unsigned DEFAULT '0' NOT NULL,
	multiplefiles_2 int(11) unsigned DEFAULT '0' NOT NULL,
	multiplefiles_3 int(11) unsigned DEFAULT '0' NOT NULL,
	multiplefiles_4 int(11) unsigned DEFAULT '0' NOT NULL,
	multiplefiles_5 int(11) unsigned DEFAULT '0' NOT NULL,
	multiplefiles_6 int(11) unsigned DEFAULT '0' NOT NULL,
	multipleimages_1 int(11) unsigned DEFAULT '0' NOT NULL,
	multipleimages_2 int(11) unsigned DEFAULT '0' NOT NULL,
	multipleimages_3 int(11) unsigned DEFAULT '0' NOT NULL,
	multipleimages_4 int(11) unsigned DEFAULT '0' NOT NULL,
	multipleimages_5 int(11) unsigned DEFAULT '0' NOT NULL,
	multipleimages_6 int(11) unsigned DEFAULT '0' NOT NULL,
	text_1 text NOT NULL,
	text_2 text NOT NULL,
	text_3 text NOT NULL,
	text_4 text NOT NULL,
	text_5 text NOT NULL,
	text_6 text NOT NULL,
	input_1 text NOT NULL,
	input_2 text NOT NULL,
	input_3 text NOT NULL,
	input_4 text NOT NULL,
	input_5 text NOT NULL,
	input_6 text NOT NULL,
	link_1 text NOT NULL,
	link_2 text NOT NULL,
	link_3 text NOT NULL,
	link_4 text NOT NULL,
	link_5 text NOT NULL,
	link_6 text NOT NULL,
	dropdown int(11) unsigned DEFAULT '0' NOT NULL,
	checkbox int(11) unsigned DEFAULT '0' NOT NULL,
	radiobutton int(11) unsigned DEFAULT '0' NOT NULL
);